baseurl = "https://32fifthstyling.com/"
languageCode = "en-us"
title = "32 Fifth Styling"
theme = "hugo-creative-theme"
googleAnalytics = "UA-118016125-1"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  name = "32 Fifth Styling"
  description = "A full service styling, personal shopping, and image consultation firm"

  # The path must be relative to the static folder
  favicon = "favicon.ico"


  # Navigation
  [params.navigation]
    brand = "32 Fifth Styling"

    [params.navigation.links]
      about     = "About"
      services  = "Services"
      portfolio = "Portfolio"
      contact   = "Contact"


  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "32 Fifth Styling"
    subtitle   = "A full service styling, personal shopping, and image consultation firm designed to help you become your most confident self."
    buttonText = "Find out more"


  # About section
  [params.about]
    headline    = "About Lauren"
    description = "Lauren is a New York City-based personal stylist. A New Hampshire native with a lifelong love of clothes, she studied Communications and Fashion Merchandising at Marist College. After spending nearly ten years working in Marketing and Communications, Lauren's love of styling was reignited after helping a friend revamp her wardrobe for a new job, and thus, 32 Fifth was born!<br></br><br>Lauren is a Bridal Stylist at BHLDN and is pursuing a Personal Style Certificate from The New York Institute of Art & Design."
    buttonText  = "Get started!"


  # Service section
  [params.services]
    headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Closet Edit"
            description = "Stop claiming you have nothing to wear and learn to love everything in your closet"

        [[params.services.list]]
      icon = "fa-shopping-bag"
      title = "Personal Shopping"
      description = "Shopping that's actually effective"

    [[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Style & Color Analysis"
            description = "Learn what actually looks good on you"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Event Styling"
            description = "Develop a look that makes you feel confident in those important moments"


    # Portfolio modals
  [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
  [params.aside]
    headline = "Learn More About Services & Pricing"

    [params.aside.button]
      text = "Download now"
      link = "32fifthstyling.com/32 Fifth Service Guide.pdf"

     # Contact section
   [params.contact]
     headline = "Get In Touch!"
     description = "Have a question? Interested in working together? Just want to say hello? That's great! Send me an email and I will get back to you as soon as possible!"
     phone = "603-540-1950"
     email = "lauren@32fifthstyling.com"
